use_frameworks!

target 'PGRequest_Example' do
  pod 'PGRequest', :path => '../'

  target 'PGRequest_Tests' do
    inherit! :search_paths

    pod 'Alamofire', '~> 5.0'
    pod 'RxSwift', '~> 5.0'
    pod 'RxCocoa', '~> 5.0'
  end
end
