use_frameworks!

target 'PGRequest_Example' do
  pod 'PGRequest', :path => '../'

  target 'PGRequest_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
